Apply last example_ynh

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,58 +1,156 @@
 #!/bin/bash
 
 #=================================================
-# GENERIC STARTING
+# GENERIC START
 #=================================================
 # IMPORT GENERIC HELPERS
 #=================================================
 
-# Source YunoHost helpers
-source /usr/share/yunohost/helpers
-source _future.sh
 source _common.sh
+source /usr/share/yunohost/helpers
 
 #=================================================
 # LOAD SETTINGS
 #=================================================
+ynh_script_progression --message="Loading installation settings..."
 
-# Retrieve arguments
 export app=$YNH_APP_INSTANCE_NAME
-export domain=$(ynh_app_setting_get "$app" domain)
-export app_version=$(ynh_app_setting_get "$app" app_version)
-export oca=$(ynh_app_setting_get "$app" oca)
-export port=$(ynh_app_setting_get $app port)
-export port_chat=$(ynh_app_setting_get $app port_chat)
+
+export domain=$(ynh_app_setting_get --app=$app --key=domain)
+export app_version=$(ynh_app_setting_get --app=$app --key=app_version)
+export oca=$(ynh_app_setting_get --app=$app --key=oca)
+export port=$(ynh_app_setting_get --app=$app --key=port)
+export port_chat=$(ynh_app_setting_get --app=$app --key=port_chat)
 export is_public=0
-export final_path=$(ynh_app_setting_get $app final_path)
-export conf_file=$(ynh_app_setting_get $app conf_file)
+export final_path=$(ynh_app_setting_get --app=$app --key=final_path)
+export conf_file=$(ynh_app_setting_get --app=$app --key=conf_file)
 export preinstall=0
 
 #=================================================
 # CHECK VERSION
 #=================================================
+ynh_script_progression --message="Checking version..."
 
-ynh_check_app_version_changed
+upgrade_type=$(ynh_check_app_version_changed)
 
-#=================================================
-# STANDARD UPGRADE STEPS
 #=================================================
 # BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
 #=================================================
+ynh_script_progression --message="Backing up the app before upgrading (may take a while)..."
 
 # Backup the current version of the app
 ynh_backup_before_upgrade
 ynh_clean_setup () {
-	# restore it if the upgrade fails
+	# Restore it if the upgrade fails
 	ynh_restore_upgradebackup
 }
 # Exit if an error occurs during the execution of the script
 ynh_abort_if_errors
 
+#=================================================
+# STANDARD UPGRADE STEPS
+#=================================================
+# STOP SYSTEMD SERVICE
+#=================================================
+ynh_script_progression --message="Stopping a systemd service..."
+
+ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app.log"
 
 #=================================================
-# STEP Migrations
+# ENSURE DOWNWARD COMPATIBILITY
 #=================================================
-ynh_system_user_create $app
-setup_files
-install_dependencies
-service $app restart
+ynh_script_progression --message="Ensuring downward compatibility..."
+
+# Cleaning legacy permissions
+if ynh_legacy_permissions_exists; then
+	ynh_legacy_permissions_delete_all
+
+	ynh_app_setting_delete --app=$app --key=is_public
+fi
+
+#=================================================
+# CREATE DEDICATED USER
+#=================================================
+ynh_script_progression --message="Making sure dedicated system user exists..."
+
+# Create a dedicated user (if not existing)
+ynh_system_user_create --username=$app --home_dir="$final_path"
+
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
+
+if [ "$upgrade_type" == "UPGRADE_APP" ]
+then
+	ynh_script_progression --message="Upgrading source files..."
+
+	# Download, check integrity, uncompress and patch the source from app.src
+	setup_files
+fi
+
+#=================================================
+# UPGRADE DEPENDENCIES
+#=================================================
+ynh_script_progression --message="Upgrading dependencies..."
+
+ynh_install_app_dependencies $pkg_dependencies
+
+#=================================================
+# SPECIFIC UPGRADE
+#=================================================
+# BUILD APP
+#=================================================
+ynh_script_progression --message="Building $app..."
+
+ynh_add_swap 1024
+if ! wkhtmltopdf --version | grep "wkhtmltopdf 0.12.4 (with patched qt)"; then
+    # The debian package has a bug so we deploy a more recent version
+    if [ -f '../manifest.json' ] ; then
+        ynh_setup_source /usr/
+    else
+        OLD_YNH_CWD=$YNH_CWD
+        YNH_CWD=$YNH_CWD/../settings/conf
+        ynh_setup_source /usr/
+        YNH_CWD=$OLD_YNH_CWD
+    fi
+fi
+pushd $final_path
+    if grep "python3" $final_path/$appname/$FORKNAME-bin ; then
+        python3 -m venv venv
+        venv/bin/pip3 install wheel
+        venv/bin/pip3 install -r $appname/requirements.txt
+    else
+        virtualenv venv
+        venv/bin/pip install wheel
+        venv/bin/pip install -r $appname/requirements.txt
+    fi
+popd
+
+#=================================================
+# GENERIC FINALIZATION
+#=================================================
+# INTEGRATE SERVICE IN YUNOHOST
+#=================================================
+ynh_script_progression --message="Integrating service in YunoHost..."
+
+yunohost service add $app --log="/var/log/$app.log"
+
+#=================================================
+# START SYSTEMD SERVICE
+#=================================================
+ynh_script_progression --message="Starting a systemd service..."
+
+ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app.log"
+
+#=================================================
+# RELOAD NGINX
+#=================================================
+ynh_script_progression --message="Reloading NGINX web server..."
+
+ynh_systemd_action --service_name=nginx --action=reload
+
+#=================================================
+# END OF SCRIPT
+#=================================================
+
+ynh_script_progression --message="Upgrade of $app completed"
